<a href="https://colab.research.google.com/github/PawanBadak/PDS-Practicals/blob/main/Practical_3(A_74).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PDS Practical-3**

Name: Pavan Ankush Badak

Div:SY-A

Roll No:A-74

Aim: Data Wrangling with pandas: Manipulate and transform data to suit the analysis needs.

**Theory:**
Data wrangling is the process of transforming and organizing raw data into a structured and meaningful format for analysis. In Python, the Pandas library is widely used for data wrangling because it provides powerful tools to manipulate datasets efficiently through DataFrames and Series.

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

print("Original DataFrame head:")
display(df.head())

# Save to CSV and reload (as per previous notebook state)
df.to_csv("titanic.csv", index=False)
df = pd.read_csv("titanic.csv")

print("DataFrame info after loading:")
df.info()

print("Missing values before wrangling:")
print(df.isnull().sum())

# Fill missing Age with mean (addressing the FutureWarning from before)
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Drop Cabin column
df.drop("Cabin", axis=1, inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

print("Missing values after filling Age and dropping Cabin:")
print(df.isnull().sum())

# Create new column 'Age_Double'
df["Age_Double"] = df["Age"] * 2

print("DataFrame head after creating 'Age_Double' column:")
display(df.head())

print("Passengers with Age > 30:")
display(df[df["Age"] > 30].head())

print("DataFrame sorted by Age (descending):")
display(df.sort_values(by="Age", ascending=False).head())

print("Mean Age by Pclass:")
print(df.groupby("Pclass")["Age"].mean())

print("Final DataFrame head:")
display(df.head())

Original DataFrame head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

DataFrame info after loading:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
Missing values before wrangling:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
Missing values after filling Age and dropping Cabin:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64
DataFrame head after creating 'Age_Double' column:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Double
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,44.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,76.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,52.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,70.0

Passengers with Age > 30:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Double
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,76.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,70.0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,108.0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,116.0

DataFrame sorted by Age (descending):

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Double
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,S,160.0
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,S,148.0
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,C,142.0
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,C,142.0
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,Q,141.0

Mean Age by Pclass:
Pclass
1    37.048118
2    29.866958
3    26.403259
Name: Age, dtype: float64
Final DataFrame head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Double
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,44.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,76.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,52.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,70.0

Q 1. What is Data Wrangling? Difference from Data Preprocessing

 Answer:
Data wrangling is the process of cleaning, transforming, and organizing raw data into a structured format suitable for analysis.


 Difference:
Feature Data Wrangling Data Preprocessing Purpose Clean & transform raw data Prepare data for machine learning Tasks Handling missing data, filtering, reshaping Scaling, encoding, normalization Stage Initial stage Before model training

Q2. Importance of EDA in Pandas

Exploratory Data Analysis (EDA) is a crucial step in any data analysis project, and Pandas provides excellent tools for it. Here's why EDA is important:

Understand Data Structure: EDA helps you understand the format, structure, and types of data (e.g., numerical, categorical, dates) within your Pandas DataFrame.
Identify Missing Values: You can easily pinpoint missing data points and decide on strategies to handle them (e.g., imputation, deletion).
Detect Outliers: EDA helps in identifying unusual data points that might skew your analysis or model training, which can then be investigated or treated.
Discover Patterns and Relationships: By visualizing and summarizing data, you can uncover hidden patterns, correlations between variables, and trends that might not be obvious at first glance.

Q3. Difference between Series, DataFrame, and Panel



Let's break down the differences between Series, DataFrame, and Panel in Pandas:

Series:

1-dimensional labeled array: Think of it like a single column in a spreadsheet or a Python list with an added index.
Homogeneous data: All elements in a Series must be of the same data type (e.g., all integers, all strings, all floats).
Structure: It has a data component and an index component.
Analogy: A single column of data with row labels.
Use cases: Storing a single variable's data, time series data, or as a component of a DataFrame.
DataFrame:

2-dimensional labeled data structure: It's the most commonly used Pandas object, resembling a table or spreadsheet.
Heterogeneous data: Each column can have a different data type, but all elements within a single column must be of the same type.
Structure: Composed of multiple Series, where each Series represents a column. It has both row (index) and column labels.
Analogy: A spreadsheet with rows and columns, where each column can hold different types of data.
Use cases: Storing tabular data, performing data cleaning, manipulation, and analysis.
Panel:

Q 4. Functions Explanation

a) isnull()


 Used to check missing values
df.isnull()


b) notnull()
 Opposite of isnull(), checks non-missing values
df.notnull()


c) dropna()
 Removes rows or columns with missing values
df.dropna()


d) fillna()
Fills missing values with a specific value
df.fillna(0)

Q 5. Column Transformation


 Answer:
Column transformation means modifying existing columns or creating new columns from existing data.


 Importance:


● Helps in feature creation

● Makes data suitable for analysis

● Improves model performance

 Example:
df["Age_Double"] = df["Age"] * 2

Conclusion

Data wrangling with Pandas is an essential step in the data analysis process, as it prepares raw data for meaningful insights. By using various functions and operations, data can be cleaned, transformed, and organized efficiently. Proper data wrangling improves the accuracy and quality of analysis, making it easier to extract valuable information. Thus, mastering Pandas for data wrangling is crucial for effective data analysis and decision-making.