# **PDS Practical-2**

Name: Pavan Ankush Badak

---


Div:SY-A

---


Roll No:A-74


---

Aim:
To perform data ingestion and cleaning using Pandas.

**Theory:**
Data ingestion is the process of collecting and importing data from various sources into a system for analysis. These sources can include databases, CSV files, APIs, web scraping, or real-time streaming data. The main goal of data ingestion is to gather raw data and store it in a structured format so it can be easily accessed and analyzed. In Python, libraries like Pandas are commonly used to load data using functions such as read_csv(), read_excel(), or read_json().

Q 1). What is data ingestion and why is it important?

-> Answer:
Data ingestion is the process of collecting and importing data from different sources such as CSV files, databases, or APIs into a system for analysis.

Importance:

● It is the first step in data science

● Makes data available for processing

● Ensures data is organized and accessible
* Library Used:
The most commonly used Python library for data ingestion and cleaning is Pandas.

Q 2. Why is data cleaning necessary?
-> Answer:
Data cleaning is necessary to improve the quality of data before analysis or machine learning.
* Reasons:

 Removes missing values

Fixes incorrect or inconsistent data

 Removes duplicate entries

 Ensures accurate results




* Without cleaning, analysis can give wrong results.

Q 3. How do you load a CSV file into a Pandas DataFrame?

->Answer:
A CSV file can be loaded into a Pandas DataFrame using the read_csv() function. *Example:
import pandas as pd
df = pd.read_csv("file_name.csv")
* This reads the CSV file and stores it in a DataFrame.

Q4. Difference between head() and tail()

The head() function in Pandas displays the first five rows of a DataFrame by default, which is useful for a quick initial inspection of the data. On the other hand, the tail() function displays the last five rows of a DataFrame by default, which is useful for checking the end of the dataset, especially after operations that might append data.

Both functions are excellent for quickly getting a sense of your data's structure and content without printing the entire DataFrame.

Q 5. How to identify missing values?

-> Answer:
Missing values in a dataset can be identified using the isnull() function.
* Example:
df.isnull().sum()
* Explanation:

● isnull() → returns True/False for missing values

● sum() → counts total missing values in each column

**1. What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning?**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
url = '/content/train (1).csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
age_column = df['Age']

age_column.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [ ]:
df['date'] = '14 Apr 1912'

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912

In [ ]:
sorted_df = df.sort_values(by='Fare', ascending=False)

sorted_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14 Apr 1912
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,14 Apr 1912
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14 Apr 1912
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,14 Apr 1912
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,14 Apr 1912

In [ ]:
sorted_df = df.sort_values(by='Fare', ascending=False)

sorted_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14 Apr 1912
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,14 Apr 1912
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14 Apr 1912
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,14 Apr 1912
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,14 Apr 1912

In [ ]:
df_renamed = df.rename(columns={
    'Sex': 'Gender',
    'Pclass': 'Passenger_Class'
})

df_renamed.head()

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
filtered_df = df[(df['Age'] > 30) & (df['Fare'] > 50)]

filtered_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,14 Apr 1912
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,14 Apr 1912
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,14 Apr 1912

In [ ]:
filtered_df = df[(df['Age'] > 30) & (df['Fare'] > 50)]

filtered_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,14 Apr 1912
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,14 Apr 1912
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,14 Apr 1912

In [ ]:
grouped = df.groupby('Sex')['Fare'].mean()

grouped

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [ ]:
df2 = df[['PassengerId', 'Survived']]

merged_df = pd.merge(df, df2, on='PassengerId')

merged_df.head()

,PassengerId,Survived_x,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date,Survived_y
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912,0

In [ ]:
df_dropped = df.drop(columns=['Cabin'])

df_dropped_rows = df.dropna(subset=['Age'])

df_dropped.head()
df_dropped_rows.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912

## Conclusion

This practical successfully demonstrated the process of data ingestion and cleaning using the Pandas library in Python. We covered essential steps including:

*   **Data Loading:** Ingesting data from a CSV file into a Pandas DataFrame.
*   **Initial Data Inspection:** Using `head()`, `tail()`, and `info()` to understand the dataset's structure and contents.
*   **Missing Value Identification:** Utilizing `isnull().sum()` to pinpoint missing data across columns.
*   **Data Cleaning Techniques:** Applying methods to handle missing values by filling them (e.g., with the mean) and dropping columns with excessive missing data (`Cabin` column).
*   **Duplicate Removal:** Ensuring data uniqueness by dropping duplicate rows.

Through these steps, the raw dataset was transformed into a cleaner, more usable format, ready for further analysis or machine learning tasks. This practical highlights the importance of thorough data preparation as a foundational step in any data science workflow.